/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: "var(--canvas)",
        surface: "var(--surface)",
        panel: "var(--panel)",
        track: "var(--track)",
        tile: "var(--tile)",
        well: "var(--well)",
        line: "var(--line)",
        "line-strong": "var(--line-strong)",
        "graph-bg": "var(--graph-bg)",
        "graph-dot": "var(--graph-dot)",
        ink: {
          DEFAULT: "var(--ink)",
          2: "var(--ink-2)",
          3: "var(--ink-3)",
          4: "var(--ink-4)",
          inverse: "var(--ink-inverse)",
        },
        header: {
          DEFAULT: "var(--header-bg)",
          line: "var(--header-line)",
          muted: "var(--header-muted)",
        },
        indigo: {
          DEFAULT: "var(--indigo)",
          press: "var(--indigo-press)",
          deep: "var(--indigo-deep)",
          text: "var(--indigo-text)",
          surface: "var(--indigo-surface)",
          "on-dark": "var(--indigo-on-dark)",
          "badge-text": "var(--indigo-badge-text)",
        },
        teal: {
          DEFAULT: "var(--teal)",
          strong: "var(--teal-strong)",
          surface: "var(--teal-surface)",
          text: "var(--teal-text)",
          "on-dark": "var(--teal-on-dark)",
        },
        amber: {
          DEFAULT: "var(--amber)",
          strong: "var(--amber-strong)",
          surface: "var(--amber-surface)",
          text: "var(--amber-text)",
          line: "var(--amber-line)",
          "on-dark": "var(--amber-on-dark)",
          "warn-bg": "var(--amber-warn-bg)",
          "warn-text": "var(--amber-warn-text)",
        },
        red: {
          DEFAULT: "var(--red)",
          strong: "var(--red-strong)",
          text: "var(--red-text)",
          surface: "var(--red-surface)",
          wash: "var(--red-wash)",
          line: "var(--red-line)",
        },
        slate: {
          DEFAULT: "var(--slate)",
          surface: "var(--slate-surface)",
          text: "var(--slate-text)",
        },
        code: {
          bg: "var(--code-bg)",
          bar: "var(--code-bar)",
          text: "var(--code-text)",
          muted: "var(--code-muted)",
          track: "var(--code-track)",
          line: "var(--code-line)",
        },
      },
      borderRadius: {
        xs: "var(--r-xs)",
        sm: "var(--r-sm)",
        md: "var(--r-md)",
        lg: "var(--r-lg)",
        xl: "var(--r-xl)",
        "2xl": "var(--r-2xl)",
        pill: "var(--r-pill)",
      },
      boxShadow: {
        1: "var(--sh-1)",
        2: "var(--sh-2)",
        3: "var(--sh-3)",
        4: "var(--sh-4)",
        shell: "var(--sh-shell)",
        indigo: "var(--sh-indigo)",
      },
      fontFamily: {
        display: ["var(--font-display)"],
        sans: ["var(--font-sans)"],
        mono: ["var(--font-mono)"],
      },
      maxWidth: {
        workspace: "1152px",
        header: "1200px",
        summary: "840px",
        landing: "640px",
      },
      transitionTimingFunction: {
        standard: "var(--ease-standard)",
        out: "var(--ease-out)",
        in: "var(--ease-in)",
        sheet: "var(--ease-sheet)",
        spring: "var(--spring-snap)",
      },
      transitionDuration: {
        instant: "var(--dur-instant)",
        fast: "var(--dur-fast)",
        base: "var(--dur-base)",
        slow: "var(--dur-slow)",
        spring: "var(--dur-spring)",
      },
    },
  },
  plugins: [],
};
